[windows]
# Ajoutez vos machines ici avec leurs identifiants spécifiques
192.168.56.20 ansible_user=Administrator ansible_password=064872470

# Exemple d'une autre machine avec un compte différent
# 192.168.56.21 ansible_user=AdminWazuh ansible_password=MonMotDePasseSecret

[windows:vars]
# Configuration globale pour WinRM sur HTTP (port 5985)
ansible_connection=winrm
ansible_port=5985
ansible_winrm_scheme=http
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=ntlm
