---
- hosts: all
  become: yes
  tasks:
    - name: Déployer les règles auditd
      ansible.builtin.copy:
        src: audit.rules
        dest: /etc/audit/rules.d/audit.rules
        owner: root
        group: root
        mode: '0640'
      notify: Reload auditd rules

    - name: Déployer la configuration de Wazuh
      ansible.builtin.copy:
        src: ossec.conf
        dest: /var/ossec/etc/ossec.conf
        owner: root
        group: wazuh
        mode: '0660'
      notify: Restart wazuh-agent

    - name: Installer le paquet jq (requis par le script active response)
      ansible.builtin.apt:
        name: jq
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Déployer le script Active Response remove-threat.sh
      ansible.builtin.copy:
        src: remove-threat.sh
        dest: /var/ossec/active-response/bin/remove-threat.sh
        owner: root
        group: wazuh
        mode: '0750'

    - name: Créer le lien remove-threat vers remove-threat.sh
      ansible.builtin.file:
        src: /var/ossec/active-response/bin/remove-threat.sh
        dest: /var/ossec/active-response/bin/remove-threat
        owner: root
        group: wazuh
        state: link
        force: true

  handlers:
    - name: Reload auditd rules
      ansible.builtin.command:
        cmd: augenrules --load

    - name: Restart wazuh-agent
      ansible.builtin.service:
        name: wazuh-agent
        state: restarted
